importing Numpy

In [2]:
import numpy as np

In [3]:
a = np.array(5)
a

array(5)

In [4]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
print(a.shape)
a = a.reshape(3, 5)
a.shape

(15,)


(3, 5)

In [7]:
a.ndim

2

In [8]:
a.size

15

In [9]:
a.dtype

dtype('int64')

In [10]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
a = a.reshape(2, 5, 2)

In [12]:
a.ndim

3

In [13]:
np.zeros((3, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.ones((3, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [19]:
b = np.array([10, 20, 30, 40])
b

array([10, 20, 30, 40])

In [23]:
a + b

array([10, 21, 32, 43])

In [24]:
a - b

array([-10, -19, -28, -37])

In [25]:
a * b

array([  0,  20,  60, 120])

In [26]:
a > b

array([False, False, False, False])

In [27]:
a == b

array([False, False, False, False])

In [28]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [29]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])