importing Numpy

In [25]:
import numpy as np

In [26]:
a = np.array(5)
a

array(5)

In [27]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
print(a.shape)
a = a.reshape(3, 5)
a.shape

(15,)


(3, 5)

In [30]:
a.ndim

2

In [31]:
a.size

15

In [32]:
a.dtype

dtype('int64')

In [33]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
a = a.reshape(2, 5, 2)

In [35]:
a.ndim

3

In [36]:
np.zeros((3, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
np.ones((3, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [39]:
b = np.array([10, 20, 30, 40])
b

array([10, 20, 30, 40])

In [40]:
a + b

array([10, 21, 32, 43])

In [41]:
a - b

array([-10, -19, -28, -37])

In [42]:
a * b

array([  0,  20,  60, 120])

In [43]:
a > b

array([False, False, False, False])

In [44]:
a == b

array([False, False, False, False])

In [45]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [46]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [47]:
np.random.rand(6, 4)

array([[0.31948324, 0.76960659, 0.98775767, 0.3303563 ],
       [0.5890343 , 0.27981166, 0.55745728, 0.384217  ],
       [0.70855868, 0.23399991, 0.38051315, 0.37922124],
       [0.99315583, 0.30906959, 0.30859169, 0.1106862 ],
       [0.41872175, 0.61570108, 0.2061448 , 0.01323738],
       [0.83532687, 0.35767578, 0.09965375, 0.72587511]])

In [48]:
np.random.randn(6, 4)
# randn will return a random number from normal curve

array([[-0.2387917 , -1.62608676,  0.93456321, -0.13648275],
       [-0.18143134, -0.52544575, -0.69027582,  0.44705675],
       [-0.68340461,  0.18058812, -1.22224823,  0.40167246],
       [ 1.21820735, -1.33056155,  0.10987158, -1.57956005],
       [-0.30774525, -0.39795932, -0.88845451, -0.16427106],
       [ 1.16658604,  0.60496598, -2.08534877, -0.59381904]])