# Sorting

|name|description|
|:-:|:-:|
| sort(a[, axis, kind, order, stable]) | Return a sorted copy of an array.
| lexsort(keys[, axis]) | Perform an indirect stable sort using a sequence of keys.
| argsort(a[, axis, kind, order, stable]) | Returns the indices that would sort an array.
| ndarray.sort([axis, kind, order]) | Sort an array in-place.
| sort_complex(a) | Sort a complex array using the real part first, then the imaginary part.
| partition(a, kth[, axis, kind, order]) | Return a partitioned copy of an array.
| argpartition(a, kth[, axis, kind, order]) | Perform an indirect partition along the given axis using the algorithm specified by the kind keyword.

[Go to documents](https://numpy.org/doc/stable/reference/routines.sort.html)

In [1]:
import numpy as np

## numpy.sort()

```python
numpy.sort(a, axis=-1, kind="quicksort", order=None, *, stable=None)
```
Return a sorted __copy__ of an array.


- `a`: array_like  
    - Array to be sorted.
    - required
- `axis`: int or None
    - default = -1 (optional)
    - int or None
    - by default try to sort last axis(-1) but you can either specify the axis you wish to sort or set `axis` to None to flattened before sorting

- `kind`: {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}
    - sorting algorithm
    - default = "quicksort" (optional)
    - Note that both ‘stable’ and ‘mergesort’ use timsort or radix sort under the covers and, in general, the actual implementation will vary with data type. The ‘mergesort’ option is retained for backwards compatibility.

    - The various sorting algorithms are characterized by their average speed, worst case performance, work space size, and whether they are stable. A stable sort keeps items with the same key in the same relative order. The four algorithms implemented in NumPy have the following properties:
        |kind|speed|worst case| work space| stable |
        |:-:|:-:|:-:|:-:|:-:
        |'quicksort'|1|$ O(n^2) $|0 | No
        |'heapsort'|3|$ O(n* \log(n))) $|0| No
        |'mergesort'|2|$ O(n* \log(n))) $|~n/2| Yes
        |'timsort'|2|$ O(n* \log(n))) $|~n/2| Yes
- `order`: str or list of str
    - When a is an array with fields defined, this argument specifies which fields to compare first, second, etc.
    - A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

In [2]:
dt = [(i, int) for i in 'abcdef']

arr = np.array([(9, 2, 3, 4, 2, 1), (7, 1, 8, 6, 2, 1)], dtype=dt)  # THIS IS NOT A 2D ARRAY

sorted_arr_based_on_a = np.sort(arr, order="a")
sorted_arr_based_on_b = np.sort(arr)
sorted_arr_based_on_c = np.sort(arr, order="c")


sorted_arr_based_on_a, sorted_arr_based_on_b, sorted_arr_based_on_c

(array([(7, 1, 8, 6, 2, 1), (9, 2, 3, 4, 2, 1)],
       dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8'), ('d', '<i8'), ('e', '<i8'), ('f', '<i8')]),
 array([(7, 1, 8, 6, 2, 1), (9, 2, 3, 4, 2, 1)],
       dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8'), ('d', '<i8'), ('e', '<i8'), ('f', '<i8')]),
 array([(9, 2, 3, 4, 2, 1), (7, 1, 8, 6, 2, 1)],
       dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8'), ('d', '<i8'), ('e', '<i8'), ('f', '<i8')]))

## numpy.lexsort() 

```python
numpy.lexsort(keys, axis=-1)
```
> Returns: indices:  ndarray of ints
Perform an indirect stable sort using a sequence of keys.

- `keys` : (k, m, n, …) array-like  
    - The k keys to be sorted. The last key (e.g, the last row if keys is a 2D array) is the primary sort key. Each element of keys along the zeroth axis must be an array-like object of the same shape.

- `axis`: 
    - int
    - default = -1 (optional)
    - axis to be indirectly sorted


start sorting from last key if elements be similar, then compare previous key for the specific index and then return an array of index

In [3]:
arr_1 = np.array([1, 5, 1, 4, 3, 4, 4])
arr_2 = np.array([9, 4, 0, 4, 0, 2, 1])

indices = np.lexsort([arr_1, arr_2])

print("indices: ".ljust(15), indices)
print("second_array:".ljust(15), arr_2[indices])
print("first_array:".ljust(15), arr_1[indices])

indices:        [2 4 6 5 3 1 0]
second_array:   [0 0 1 2 4 4 9]
first_array:    [1 3 4 4 4 5 1]


in previous example the inner key was arr_2 so it sort based on that, but its 2nd and 4th index are same (`arr_2[2] == arr_2[4]`) so it will check the other key,  
and since `arr_1[2] < arr_1[4]` it will put 2 before 4 and so on

look at the other example:

In [4]:
first_names = ["parham", "fereydon", "jamshid", "parham"]
last_names = ["Mehrabi", "zarghami", "abedini", "asemani"]

indices = np.lexsort((last_names, first_names))

sorted_names = [f"{first_names[i]} {last_names[i]}" for i in np.lexsort((last_names, first_names))]
print(*sorted_names, sep='\n')

fereydon zarghami
jamshid abedini
parham Mehrabi
parham asemani


## numpy.argsort()

```python
numpy.argsort(a, axis=-1, kind=None, order=None, *, stable=None)
```
> Returns the indices that would sort an array.

- `a`: array_like
    - Array to sort.
- `axis`: int or None
    - Axis along which to sort
    - default = -1 (optional)
- `kind`: {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}
    - sorting algorithm
- `order`: str or list of str
    - When a is an array with fields defined, this argument specifies which fields to compare first, second, etc.
    - A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

- `stable`: bool
    - sort stability
    - if True, the returned array will maintain the relative order of a values which compare as equal but if False or None, its not guaranteed
    - internally this option will select `kind='stable'`
    - default = None (Optional)


<br/>
<br/>
<br/>

Returns: index_array
- ndarray, int
- Array of indices that sort a along the specified axis. If a is one-dimensional, a[index_array] yields a sorted a. More generally, np.take_along_axis(a, index_array, axis=axis) always yields the sorted a, irrespective of dimensionality.

In [5]:
arr_2D = np.array([[3, 0, 2], [9, 7, 1]])

np.argsort(arr_2D)

array([[1, 2, 0],
       [2, 1, 0]])

in previous example the axis for the 2D array is -1 (its the default) so it will consider the last axis for sorting
so in first row, it want to change it like this: 0 2 3
as we use the result you can see it:
 

In [6]:
result = np.argsort(arr_2D)
arr_2D[0][result[0]]

array([0, 2, 3])

but if we specify previous the axis to sort the cols, the result will be like this:

In [7]:
np.argsort(arr_2D, axis=0)

array([[0, 0, 1],
       [1, 1, 0]])

this new generated result means, the first 2 elements of first row should remain on first row but the last one should go to the second row(row number 1)
and same for the last item in next row which should move back to first row like this:




$
\begin{pmatrix}
3 & 0 & 2 \\
9 & 7 & 1
\end{pmatrix} \quad \longrightarrow \quad \begin{pmatrix}
3 & 0 & 1 \\
9 & 7 & 2
\end{pmatrix}
$