# search
- numpy.argmax
- numpy.nanargmax
- numpy.argmin
- numpy.nanargmin
- numpy.where
- numpy.argwhere
- numpy.nanzero
- numpy.extract


In [1]:
import numpy as np


## numpy.argmax()

`numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)`

- `a`: array_like  
    - input array
    
- `axis`:
    - __default = None__ (optional)
    - if set to an axis will search along with the specified axis
    - if remains None(default), the index is into the __flattened__ array
    - if remain to None and get flattened index, we can access element's real index using np.unravel_index
- `out`: 
    - array
    - default = None (optional)
    - if provided, the result will be inserted into this array
    - it should be of the appropriate shape and dtype
    - if no axis is specified, out should be 0 n-dim array (an empty array)
- `keepdims`:
    - bool, optional
    - f this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the array
- will find the first max(lowest index)


In [2]:
arr = np.array([[8, 9, 5],
                [6, 5, 1],
                [9, 3, 4]])
np.argmax(arr)
# this will result 1 because flatted arr is like [8, 9, 5, 6, 5, 1, 9, 3, 4]
# 9 is max which is index 1 (it won't return 6 for other nine since it will return the first max)

# np.argmax(arr, out=np.array(0))       # if we insist to use out, however its kinda useless without axis

1

in previous example we did not specify an axis, so it flattered the array first, then found the biggest number and returned its index
we could do the search along with a specific axis like this:

In [3]:
arr = np.array([[8, 9, 5],
                [6, 5, 1],
                [9, 3, 4]])
print(arr)
np.argmax(arr, axis=0)

[[8 9 5]
 [6 5 1]
 [9 3 4]]


array([2, 0, 0])


in previous example we specified axis to 0, so it will search along with the axis 0,
so at first it select 9 for the first col and return its index, then do the same for other columns
so the result is [2 0 0] since last row in first column and first row in other columns are the biggest in axis_0  

__naturally numpy axes are like this: arr[axis_0][axis_1][axis_2] . . . so:__  

when we specify `axis = 0`, the max result are like this pattern:  
`arr[?][0], arr[?][1], arr[?][2]` where `?` will replace with index with highest output  

but if we set `axis = 1`, it will be something like this:  
`arr[0][?], arr[1][?], arr[2][?]` again the `?` will be replaced with the value with highest output  


so, in our array the ? for axis=1 should be like this:   
`arr[0][1], arr[1][0], arr[2][0]`  

so if we run np.argmax(arr, axis=1), the result should be a array like this:  
[1, 0, 0]



In [4]:
arr = np.array([[8, 9, 5],
                [6, 5, 1],
                [9, 3, 4]])
print(arr)
np.argmax(arr, axis=1)

[[8 9 5]
 [6 5 1]
 [9 3 4]]


array([1, 0, 0])

official document examples:

In [5]:
arr = np.array([[10, 11, 12],
                [13, 14, 15]])
np.argmax(arr)              # will return 5 since flatted_arr[5] or arr.reshape(6)[5] is the biggest 


5

In [6]:
arr = np.array([[10, 11, 12],
                [13, 14, 15]])
print(arr)
print(np.argmax(arr, axis=0))
print(np.argmax(arr, axis=1))

[[10 11 12]
 [13 14 15]]
[1 1 1]
[2 2]


In [7]:
arr = np.array([[10, 11, 12],
                [13, 14, 15]])
ind = np.unravel_index(np.argmax(arr, axis=None), arr.shape)
print(arr)
arr[ind]

[[10 11 12]
 [13 14 15]]


15

In [8]:
b = np.arange(6)
b[1] = 5
print(b)
np.argmax(b)  # Only the first occurrence is returned.

[0 5 2 3 4 5]


1

In [9]:
x = np.arange(24).reshape((2, 3, 4))
res = np.argmax(x, axis=1)
print(res.shape)
res = np.argmax(x, axis=1, keepdims=True)
print(res.shape)


(2, 4)
(2, 1, 4)


## numpy.nanargmax()

just like numpy.nanargmax() but will ignore np.nan 

In [10]:
arr = np.array([[np.nan, 4], [2, 3]])

print(np.argmax(arr))
print(np.nanargmax(arr))

print(np.nanargmax(arr, axis=0))
print(np.nanargmax(arr, axis=1))


0
1
[1 0]
[1 1]


## numpy.argmin() & numpy.nanargmin()
 

clearly just like argmax and nanargmax but the opposite(will return the indices of smallest instead)

## numpy.where()

`numpy.where(condition, [x, y, ]/)`  
Return elements chosen from x or y depending on condition.

__note__:  
    When only condition is provided, this function is a shorthand for `np.asarray(condition).nonzero()`.  
    __Using `nonzero` directly should be preferred__, as it behaves correctly for subclasses.  
    The rest of this documentation covers only the case where all three arguments are provided.
```python
arr = np.array([[1, 5, 3], [2, 1, 7]])
np.where(arr - 5)                   # this line and next line result the same
np.asanyarray(arr - 5).nonzero()    # this line and previous line result the same
```  


- `condition`: array_like, bool
    - where True, yield x
    - otherwise yield y

- `x, y`: array_like
    - Values from which to choose. x, y and condition need to be broadcastable to some shape.
    - either a fixed value to be broadcasted, or an array_like with same shape as condition

In [11]:
arr = np.array([1, 5, 3, 2, 1, 7])


np.where(arr > 4, "Big", "Small")

array(['Small', 'Big', 'Small', 'Small', 'Small', 'Big'], dtype='<U5')

In [12]:
arr = np.array([1, 5, 3, 2, 1, 7])
a = [1000, 2000, 3000, 4000, 5000, 6000]
np.where(arr > 4, a, "small")


array(['small', '2000', 'small', 'small', 'small', '6000'], dtype='<U21')

In [13]:
a = np.arange(10)
print(a)
np.where(a < 5, a, 10*a)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [14]:
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

## numpy.argwhere()

`numpy.argwhere(a)`  
Find the indices of array elements that are __non-zero__(or not Falsy), grouped by element.

- `a`: array_like
    - input data
- Return -> 
    - index_array: (N, a.ndim) ndarray
    - indices of elements that are non-zero
    - Indices are __grouped__ by element
    -  This array will have shape (N, a.ndim) where N is the number of non-zero items.

__note__:
- np.argwhere(a) is almost the same as` np.transpose(np.nonzero(a))`, but produces a result of the correct shape for a 0D array.
- The output of `np.argwhere` is not suitable for indexing arrays. For this purpose use `np.nonzero(a)` instead.

In [15]:
data = np.array([[10, 0, 13], [0, 17, 19]])
np.argwhere(data)
# this is not how this method supposed to be used 


array([[0, 0],
       [0, 2],
       [1, 1],
       [1, 2]])

In [16]:
data = np.array([[10, 0, 13], [0, 17, 19]])
np.argwhere(data >= 0)      # where there is no negative

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [17]:
data = np.array([[10, 0, 13], [0, 17, 19]])
np.argwhere(data >= 5)      # where equal or bigger than 5

array([[0, 0],
       [0, 2],
       [1, 1],
       [1, 2]])

## numpy.nonzero()

`numpy.nonzero(a)`  
Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of a, containing the indices of the non-zero elements in that dimension. The values in a are always tested and returned in row-major, C-style order.


To group the indices by element, rather than dimension, use` np.argwhere`, which returns a row for each non-zero element.

A common use for nonzero is to find the indices of an array, where a condition is True.  
Given an array a, the condition a > 3 is a boolean array and since False is interpreted as 0, np.nonzero(a > 3) yields the indices of the a where the condition is true.

nonzero can also be called as a method of the array.

__note__:
- While the nonzero values can be obtained with `a[nonzero(a)]`, it is recommended to use `x[x.astype(bool)]` or `x[x != 0]` instead, which will correctly handle 0-d arrays.

In [18]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)
np.nonzero(x)

[[3 0 0]
 [0 4 0]
 [5 6 0]]


(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [19]:
print(x[np.nonzero(x)])
np.transpose(np.nonzero(x))

[3 4 5 6]


array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]])

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a > 3)
np.nonzero(a > 3)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
a[np.nonzero(a > 3)]    # better not to use
a[a > 3]                # prefer this spelling

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4, 5, 6, 7, 8, 9])

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
(a > 3).nonzero()       # nonzero can also be called as a method of the array.


[[1 2 3]
 [4 5 6]
 [7 8 9]]


(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

## numpy.exreact()


`numpy.extract(condition, arr)`   
Return the elements of an array that satisfy some condition.

This is equivalent to `np.compress(ravel(condition), ravel(arr))`.

If condition is boolean `np.extract()` is equivalent to `arr[condition]`.

Note that `np.place` does the __exact opposite__ of `np.extract()`.

- `condition`: array_like
    - An array whose nonzero or True entries indicate the elements of arr to extract.
- `arr`: array_like
    - Input array of the same size as condition.

In [23]:
arr = np.arange(12).reshape((3, 4))
print(arr)
condition = np.mod(arr, 3) == 0     
print(condition)
np.extract(condition, arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ True False False  True]
 [False False  True False]
 [False  True False False]]


array([0, 3, 6, 9])