# Array creation

- Array creation routines
- Array creation from existing data


## we are going to check array creation routine methods here:

In [1]:
import numpy as np


def cleaner_print(*args, end=f'\n\n {50 * "-"}\n\n', **kwargs) -> None:
    "cleaner print for clarity"
    print(*args, end=end,sep=':\n ' , **kwargs)


## np.empty:
```empty(shape[, dtype, order]) -> return a new array of given shape and type, without initializing entries```


In [2]:
arr = np.empty(5)
cleaner_print(arr.dtype, arr)

arr = np.empty(5, dtype='i1')
cleaner_print(arr.dtype, arr)

arr = np.empty(5, dtype=int)
cleaner_print(arr.dtype, arr)

arr = np.empty(5, dtype='S')
cleaner_print(arr.dtype, arr)

arr = np.empty(5, dtype='f')
cleaner_print(arr.dtype, arr)

arr = np.empty(5, dtype='f2')
cleaner_print(arr.dtype, arr)



float64:
 [4.63934335e-310 0.00000000e+000 4.63832054e-310 4.63832054e-310
 0.00000000e+000]

 --------------------------------------------------

int8:
 [1 0 1 1 0]

 --------------------------------------------------

int64:
 [93901354787118              0 93880652901712 93880652901792
              0]

 --------------------------------------------------

|S1:
 [b'\x01' b'' b'\x01' b'\x01' b'']

 --------------------------------------------------

float32:
 [9.730507e-34 4.562207e-41 9.730507e-34 4.562207e-41 6.411032e+06]

 --------------------------------------------------

float16:
 [-8.496e-02  1.413e-04        nan  0.000e+00  9.844e-01]

 --------------------------------------------------



In [3]:
# we can also change the shape:

arr = np.empty(5, dtype='i1')
cleaner_print(arr.dtype, arr)

arr = np.empty([3, 4], dtype='i1')
cleaner_print(arr.dtype, arr)

int8:
 [0 0 0 0 0]

 --------------------------------------------------

int8:
 [[  0 -83 -95   8]
 [ 45 127   0   0]
 [  0 -83 -95   8]]

 --------------------------------------------------



there is also a empty_like method which is just like empty method but it accept a prototype as a pattern  
the prototype can be in different formats:

In [4]:
proto = ([1., 2., 3.], [4., 5., 6.])
arr = np.empty_like(proto)
cleaner_print(arr.dtype, arr)


np_proto = np.array([[1., 2., 3.], [4., 5., 6.]])
arr = np.empty_like(np_proto)
cleaner_print(arr.dtype, arr)


float64:
 [[6.90858885e-310 6.90858885e-310 0.00000000e+000]
 [0.00000000e+000 1.20953760e-312 2.25527773e+180]]

 --------------------------------------------------

float64:
 [[ 6.90858885e-310  4.63832018e-310  6.90858628e-310]
 [ 4.63832017e-310 -8.55114857e-030  6.90858628e-310]]

 --------------------------------------------------



## np.eye:  
```np.eye(N[, M, k, dtype, order])  -> returns a 2-D  array with ones on the diagonal and zeros elsewhere ```

In [5]:
arr = np.eye(4)
print(arr)

arr = np.eye(3, dtype=int)
print(arr)

arr = np.eye(3, dtype=bool)
print(arr)


arr = np.eye(3, dtype=str)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ True False False]
 [False  True False]
 [False False  True]]
[['1' '' '']
 ['' '1' '']
 ['' '' '1']]


__but how to handle not squared like matrices?__  
we can use 'k' argument, its default value is 0 and it indicates the starting index

In [6]:



arr = np.eye(4,5, dtype=str)
cleaner_print(arr)


arr = np.eye(4,5, dtype=str, k=1)
cleaner_print(arr)

arr = np.eye(4,5, dtype=str, k=-1)
cleaner_print(arr)

[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']]

 --------------------------------------------------

[['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]

 --------------------------------------------------

[['' '' '' '' '']
 ['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']]

 --------------------------------------------------



## npm.identity
returns the identity array

In [7]:
arr = np.identity(5, dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## npm.ones
``` ones(shape[, dtype, order]) -> returns an array of ones with the given shape and type, filled with ones  ```

In [8]:
arr = np.ones(5)
cleaner_print(arr)

arr = np.ones([5,5])
cleaner_print(arr)

# there is also a like method for ones too

[1. 1. 1. 1. 1.]

 --------------------------------------------------

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 --------------------------------------------------



## npm.zeros
just opposite the ones  
``` zeros(shape[, dtype, order]) -> returns an array of zeros with the given shape and type, filled with zeros  ```

In [9]:
arr = np.zeros(5)
cleaner_print(arr)

arr = np.zeros([5,5])
cleaner_print(arr)

# there is also a like method for zeros too

[0. 0. 0. 0. 0.]

 --------------------------------------------------

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 --------------------------------------------------



## npm.full
this one just like the ones and zeros but with a costume value, you can declare how to fill the array

In [10]:
arr = np.full(5, 'parham')
cleaner_print(arr)

arr = np.full([5,5], 'parham')
cleaner_print(arr)

arr = np.full([5,5], 'parham', dtype='U3')
cleaner_print(arr)


# there is also a like method for full too

['parham' 'parham' 'parham' 'parham' 'parham']

 --------------------------------------------------

[['parham' 'parham' 'parham' 'parham' 'parham']
 ['parham' 'parham' 'parham' 'parham' 'parham']
 ['parham' 'parham' 'parham' 'parham' 'parham']
 ['parham' 'parham' 'parham' 'parham' 'parham']
 ['parham' 'parham' 'parham' 'parham' 'parham']]

 --------------------------------------------------

[['par' 'par' 'par' 'par' 'par']
 ['par' 'par' 'par' 'par' 'par']
 ['par' 'par' 'par' 'par' 'par']
 ['par' 'par' 'par' 'par' 'par']
 ['par' 'par' 'par' 'par' 'par']]

 --------------------------------------------------

