# Array creation

- Array creation routines
- Array creation from existing data
<small> we checked routines in previous module </small>

## now we are going to check __Array creation from existing data__ (1):

the first 3 method we are going to check are : 
- np.array:
    - np.array(object[, dtype, copy, order, subok, ndim])
- np.asarray
    - np.asarray(object[, dtype, order])
- np.asanyarray
    - np.asanyarray(object[, dtype, order])

### np.array:
__np.array(object[, dtype, copy, order, subok, ndim])__
- object: some kind of iterable as source (array_like) __required__
- dtype: The desired data-type for the array
- copy:
    - boolean
    - default is True
    - either copy the array or just reference it 
- order:
    - {‘K’, ‘A’, ‘C’, ‘F’}
    - default is 'K'
    - specify memory layout of the array
    - if object is not an array:
        - the newly created array will be in C order (row major), unless 'F' is specified in which case it will be in Fortran order (column major)

    - if object is an array:
        - order='K' & copy = True -> F & C order preserved, otherwise most similar order
        - order='K' & copy = False -> unchanged  
        <br/>
        - order='A' & copy = True -> F order if input is F and not C, otherwise C order
        - order='A' & copy = False -> unchanged  
        <br/>
        - order='C' -> C order  
        <br/>
        - order='F' -> F order  

- subok:
    - boolean
    - default is False
    - if True: then sub-classes will be passed-through.
    - if False: the returned array will be forced to be a base-class array.

- ndim:
    - int
    - default is 0
    - Specifies the minimum number of dimensions that the resulting array should have. Ones will be prepended to the shape as needed to meet this requirement.


In [1]:
import numpy as np

### lets check copy and subok argument here:

In [2]:
arr = np.array([1, 2, 3])
arr2 = np.array(arr)

print("have same id(): ", id(arr) == id(arr2))
print('may share memory: ', np.may_share_memory(arr, arr2))
print(f"{arr} is {arr2}: ", arr is arr2)

have same id():  False
may share memory:  False
[1 2 3] is [1 2 3]:  False


In [3]:
arr = np.array([1, 2, 3])
arr2 = np.array(arr, copy=False)

print("have same id(): ", id(arr) == id(arr2))
print('may share memory: ', np.may_share_memory(arr, arr2))
print(f"{arr} is {arr2}: ", arr is arr2)

have same id():  True
may share memory:  True
[1 2 3] is [1 2 3]:  True


in second scenario, if we modify the second, the first one will change too

In [4]:
arr = np.array([1, 2, 3])
arr_false_copy = np.array(arr, copy=False)
arr_true_copy = np.array(arr, copy=False)


print(arr)
arr_false_copy[0] = 4   # this will change arr too
arr_true_copy[1] = 5    # but this one will only modify arr_true_copy
print(arr)



[1 2 3]
[4 5 3]


how ever if we change type, it will copy it anyway

In [5]:
arr = np.array([1, 2, 3])
arr2 = np.array(arr, copy=False, dtype=np.int32)

print("have same id(): ", id(arr) == id(arr2))
print('may share memory: ', np.may_share_memory(arr, arr2))
print(f"{arr} is {arr2}: ", arr is arr2)

have same id():  False
may share memory:  False
[1 2 3] is [1 2 3]:  False


In [6]:
mat = np.matrix([1, 2, 3])
arr = np.array(mat)

print("have same id(): ", id(mat) == id(arr))
print('may share memory: ', np.may_share_memory(mat, arr))
print(f"{mat} is {arr}: ", mat is arr)

have same id():  False
may share memory:  False
[[1 2 3]] is [[1 2 3]]:  False


__well this one was clear, but what if we dont copy it?__  
 in this casethey both have some place in memory and some of the place is shared

In [7]:
mat = np.matrix([1, 2, 3])
arr = np.array(mat, copy=False)

print("have same id(): ", id(mat) == id(arr))               # False
print('may share memory: ', np.may_share_memory(mat, arr))  # True
print(f"{mat} is {arr}: ", mat is arr)                      # False

have same id():  False
may share memory:  True
[[1 2 3]] is [[1 2 3]]:  False


In [8]:
# in this case we also change the parent by modifying the child too:

print(mat)
arr[0] = 10
print(mat)

[[1 2 3]]
[[10 10 10]]


we saw if we dont copy (copy=False) and they were different classes like matrix and array, they would have different IDs and just share some memory,
```
id(mat) == id(arr) -> # False
```

but if we put subok=True, they will change the class of child too,  
in other words, however we are creating it using np.array, but since we specify subok=True,
it will be an object from matrix class in this case:

In [9]:
mat = np.matrix([1, 2, 3])
mat2 = np.array(mat, copy=False, subok=True)

print("have same id(): ", id(mat) == id(mat2))
print('may share memory: ', np.may_share_memory(mat, mat2))  
print(f"{mat} is {mat2}: ", mat is mat2) 
print(mat2)

have same id():  True
may share memory:  True
[[1 2 3]] is [[1 2 3]]:  True
[[1 2 3]]


## np.asarray & np.asanyarray:

- __asarray:__ is basically the same as np.array but copy is set to False
    - ```np.asarray() = np.array(copy=False)```
- __asanyarray:__ is basically the same as np.array but copy is set to False and subok is set to True
    - ``` np.asanyarray() = np.array(copy=False, subok=True) ```
