# Array creation

## now we are check some other methods for __Array creation from existing data__ (2):

- np.ascontiguousarray

- np.matrix

- np.asmatrix

- np.copy

- np.frombuffer



In [1]:
import numpy as np

## np.ascontiguousarray:
ascontiguousarray(a[, dtype]) -> return a contiguous array (ndim >= 1) in memory (C order) 

<small>Note: This function returns an array with at least one-dimension (1-d) so it will not preserve 0-d arrays.</small>

In [2]:
x = np.ones((2, 3), order='F')
print("x is Fortran order: ", x.flags['F_CONTIGUOUS'])

# Calling ascontiguousarray makes a C-contiguous copy:
y = np.ascontiguousarray(x)
print("y is C order: ", y.flags['C_CONTIGUOUS'])

x is Fortran order:  True
y is C order:  True


## np.matrix
<a href="https://numpy.org/doc/1.26/reference/generated/numpy.matrix.html">It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.</a>  
its simply returns a matrix and can be used like this:
```
input: a = np.matrix('1 2; 3 4')

or like this:

np.matrix([[1, 2], [3, 4]])
```
the output will be same.

In [3]:
a = np.matrix('1 2; 3 4')
b = np.matrix([[1,2], [3, 4]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


## np.asmatrix
Interpret the input as a matrix.

Unlike matrix, asmatrix does not make a copy if the input is already a matrix or an ndarray. Equivalent to matrix(data, copy=False).



In [4]:
a = np.array([1,2,3])

b = np.matrix(a)
c = np.asmatrix(a)

a[0] = 10

print(c)
print(b)

[[10  2  3]]
[[1 2 3]]


## np.copy
__Return an array copy of the given object.__

- but this method will create a shallow copy, so if we are going to copy a nested array, we should use copy.deepcopy:


In [5]:
import copy

a = np.array([1, 'm', [2, 3, 4]], dtype=object)
b = np.copy(a)
c = copy.deepcopy(a)

a[2][0] = 100

print(b)
print(c)

[1 'm' list([100, 3, 4])]
[1 'm' list([2, 3, 4])]


## np.frombuffer

Interpret a buffer as a 1-dimensional array.

```numpy.frombuffer(buffer[, dtype=float, count=-1, offset=0, *, like=None])```

In [6]:
s = b"Hello World !"
np.frombuffer(s, dtype='S1', count=5, offset=6)

array([b'W', b'o', b'r', b'l', b'd'], dtype='|S1')