# Array creation

## last methods for __Array creation from existing data__ (3):

- np.fromfunction

- np.fromiter

- np.fromstring

- np.loadtext


In [1]:
import numpy as np

## from function:

```numpy.fromfunction(function, shape[, dtype, like])```


Construct an array by executing a function over each coordinate.

The resulting array therefore has a value fn(x, y, z) at coordinate (x, y, z).

The result of the call to function is passed back directly. Therefore the shape of fromfunction is completely determined by function. If function returns a scalar value, the shape of fromfunction would not match the shape parameter.

In [2]:
def justone(i, j):
    print(i)
    print('-----------------------------')
    print(j)
    print('-----------------------------')
    return 0

x = 3
y = 4
res = np.fromfunction(justone, (x, y))
res

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]]
-----------------------------
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
-----------------------------


0

In [3]:
np.fromfunction(lambda i, j: i, (2, 2))

array([[0., 0.],
       [1., 1.]])

In [4]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [7]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## np.fromiter

```np.fromiter(iter, dtype, [count=-1, *, like=None])```

<small>Specify count to improve performance. It allows fromiter to pre-allocate the output array, instead of resizing it on demand.</small>

In [18]:
print( 
    np.fromiter(range(5), np.int8)
        )

# A carefully constructed subarray dtype will lead to higher dimensional results:
iterable = ((x+1, x+2) for x in range(5))
np.fromiter(iterable, dtype=np.dtype((int, 2)))

[0 1 2 3 4]


array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

## np.fromstring
A new 1-D array initialized from text data in a string.  
```numpy.fromstring(string[, dtype=float, count=-1, *, sep, like=None])```
- sep: The string separating numbers in the data; extra whitespace between elements is also ignored.

In [39]:
a = np.fromstring('1 2 3', sep=' ', dtype=int)
b = np.fromstring('1, 2, 3', sep=',', dtype=int)
print(a)
print(b)

[1 2 3]
[1 2 3]


## np.loadtxt

```np.loadtxt(fname[, dtype=float, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None])```  

- fname:
    - file, str, pathlib.Path, list of str, generator.
    - if the filename extension is .gz or .bz2, the file is first decompressed.
    - Note that generators must return bytes or strings.
    - The strings in a list or produced by a generator are treated as lines.

- dtype:
    - default is float (Optional)  
    
- comments:
    - default is "#" (Optional)
    - The characters or list of characters used to indicate the start of a comment
    - None implies no comments.
    - For backwards compatibility, byte strings will be decoded as ‘latin1’.  

- delimiter:
    - default is " " (Optional)
    - The character used to separate the values
    - For backwards compatibility, byte strings will be decoded as ‘latin1’  

- convertor:
    - Converter functions to customize value parsing.
    - if converters is callable, the function is applied to all columns,  
         else it must be a dict that maps column number to a parser function

- skiprows:
    - default is 0 (Optional)
    - Skip the first skiprows lines, including comments

- usecols:
    - default is None (optional)
    - int or sequence
    - Which columns to read, with 0 being the first
        - For example, usecols = (1,4,5) will extract the 2nd, 5th and 6th columns.
    - The default is None, results in all columns being read.  

- unpack:
    - default is False (optional)
    - If True, the returned array is transposed
        -  so that arguments may be unpacked using ```x, y, z = loadtxt(...)```

- ndmin:
    - default is 0 (optional)
    - The returned array will have at least ndmin dimensions. Otherwise mono-dimensional axes will be squeezed. Legal values: 0, 1 or 2.

- encoding:
    - default is "bytes" (optional)
    - Encoding used to decode the inputfile. 
    - Does not apply to input streams. 
    - if set to None the system default is used.

- max_rows:
    - default is None (optional)
    - Read max_rows rows of content after skiprows lines
    - The default is to read all the rows.
    - empty rows containing no data such as empty lines and comment lines are not counted towards max_rows

- quotechar:
    - default is None which means quoting support is disabled
    - The character used to denote the start and end of a quoted item
    - Occurrences of the delimiter or comment characters are ignored within a quoted item
    - If two consecutive instances of quotechar are found within a quoted field, the first is treated as an escape character